name: Continuous Integration (CI) pipeline of the Cart microservice

on:
    pull_request:
        types: [opened, reopened, edited]
        branches: ["main"]
jobs:
    Build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
                cache: maven
            - name: Build with Maven
              run: |
                cd carts-microservice/
                mvn -B package --file pom.xml
            - name: verifying the project was built
              run: |
                ls
                pwd
                ls target/
            - name: Update dependency graph
              uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
            
              

